version: 2
jobs:
    build:
        docker:
          - image: circleci/node:13.5
        steps:
          - checkout
          - run: npm install @angular/cli --save-dev
          - run: npm install
          - run: ng build --prod --output-path=docs
          - run: git add docs/*
          - run: git commit -m "Updated latest deployable version for gh-pages"
          - run: git push origin master
